import { JogoVelha } from './jogo-velha';
const jogoVelha = new JogoVelha();
jogoVelha.print();
jogoVelha.play(0,0);
jogoVelha.print();
jogoVelha.play(0,2);
jogoVelha.print();
jogoVelha.play(1,1);
jogoVelha.print();
jogoVelha.play(1,2);
jogoVelha.print();
jogoVelha.play(2,2);
jogoVelha.print();
