FROM ubuntu:20.04
CMD sleep 1000000
#pra criar o container desta imagem faça
# docker build --tag tag-imagem .
#pra iniciar use
# docker run teste-image -d
#depois vc pode acessar o terminal usando um dos dois comandos abaixo:
#docker exec -it ID-CONTAINER sh
#ou
#docker exec -it ID-CONTAINER bash