name: Release Creation

on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
 
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: 'module.json'
        env:
          version: ${{github.event.release.tag_name}}
          url: https://github.com/${{github.repository}}
          manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
          download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.zip

      # Create a zip file with all files required by each  module to add to the release
      - run: zip -r ./backend.zip backend/
      - run: zip -r ./front-end-angular.zip front-end-angular/
      - run: zip -r ./front-end-vanilla.zip front-end-vanilla/
      - run: zip -r ./front-end-vue.zip front-end-vue/
      

      # Create a release for this specific version
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # Set this to false if you want to prevent updating existing releases
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './backend.zip, ./front-end-angular.zip, ./front-end-vanilla.zip, ./front-end-vue.zip' 
          body: ${{ github.event.release.body }}