export const TP_DM = 0;
;
;
;
export var GAME_SCREEN;
(function (GAME_SCREEN) {
    GAME_SCREEN[GAME_SCREEN["TP_NULL"] = -1] = "TP_NULL";
    GAME_SCREEN[GAME_SCREEN["TP_FULLSCREEN_ANSWER"] = 0] = "TP_FULLSCREEN_ANSWER";
    GAME_SCREEN[GAME_SCREEN["TP_LOAD"] = 1] = "TP_LOAD";
    GAME_SCREEN[GAME_SCREEN["TP_SPLASH"] = 2] = "TP_SPLASH";
    GAME_SCREEN[GAME_SCREEN["TP_PLAY"] = 3] = "TP_PLAY";
})(GAME_SCREEN || (GAME_SCREEN = {}));
;
;
export var GAME_SUB_SCREEN;
(function (GAME_SUB_SCREEN) {
    GAME_SUB_SCREEN[GAME_SUB_SCREEN["TP_NULL"] = 0] = "TP_NULL";
    GAME_SUB_SCREEN[GAME_SUB_SCREEN["TP_CONFIG_PAGE"] = 101] = "TP_CONFIG_PAGE";
    GAME_SUB_SCREEN[GAME_SUB_SCREEN["TP_CREDIT_PAGE"] = 102] = "TP_CREDIT_PAGE";
    GAME_SUB_SCREEN[GAME_SUB_SCREEN["TP_SOUND_PAGE"] = 103] = "TP_SOUND_PAGE";
    GAME_SUB_SCREEN[GAME_SUB_SCREEN["TP_REMOVE_PLAYER_PAGE"] = 104] = "TP_REMOVE_PLAYER_PAGE";
    GAME_SUB_SCREEN[GAME_SUB_SCREEN["TP_MAIN_PAGE"] = 1] = "TP_MAIN_PAGE";
})(GAME_SUB_SCREEN || (GAME_SUB_SCREEN = {}));
//# sourceMappingURL=types.js.map