"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CODE_UNKNOWN_MESSAGE = exports.CODE_NOT_FOUND = exports.CODE_ACCESS_DENIED = exports.CODE_SESSION_INVALID = exports.CODE_REQUEST_INVALID = exports.ERR_SESSION_INVALID = exports.ERR_APP_ID_NOT_FOUND = exports.ERR_UNKNOWN_MESSAGE = void 0;
exports.ERR_UNKNOWN_MESSAGE = "Unknown Error";
exports.ERR_APP_ID_NOT_FOUND = "APP ID Not Found";
exports.ERR_SESSION_INVALID = "Session invalid";
exports.CODE_REQUEST_INVALID = 40000;
exports.CODE_SESSION_INVALID = 40100;
exports.CODE_ACCESS_DENIED = 40300;
exports.CODE_NOT_FOUND = 40400;
exports.CODE_UNKNOWN_MESSAGE = 50000;
