DROP DATABASE IF EXISTS `test`;
CREATE DATABASE `test`;
DROP TABLE IF EXISTS `test`;
CREATE TABLE `test` (
	`id` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'armscii8_bin',
	`count` INT NOT NULL DEFAULT 0 COLLATE 'armscii8_bin',
	`type` VARCHAR(50) NOT NULL COLLATE 'armscii8_bin',
	`created` DATE NOT NULL
)
COLLATE='armscii8_bin'
ENGINE=InnoDB
;


DROP PROCEDURE IF EXISTS spFillTest;

DELIMITER $$

CREATE DEFINER=`root`@`%` PROCEDURE `spFillTest`()
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT ''
BEGIN 
	DECLARE ROWS1 INT DEFAULT 0;
	DECLARE ID INT DEFAULT 0;
	DECLARE CONT INT DEFAULT 0;
	DECLARE TYPE INT DEFAULT 0;
	
 
	WHILE ROWS1 <= 10000 DO
		SET ROWS1 = ROWS1 +1; 
      -- SELECT ROWS1; 
      
      SET ID = FLOOR(RAND() * 10000000); 
		SET TYPE = FLOOR(RAND() * 4);
		SET CONT= FLOOR(RAND() * 100); 
	
		INSERT INTO `test`.`test` (`id`, `type`, `count`, `created`) VALUES (
		CONCAT('I',CAST(ID AS VARCHAR(20))),
		CONCAT('TEC',CAST(TYPE AS VARCHAR(20))), 
		CONT,
		CAST(NOW() AS DATE));
		
	END WHILE;
 

END$$

DELIMITER ;

CALL spFillTest();

SELECT COUNT(id) FROM test;