# Configurações da Rede Neural
layers=3
#formato camadaFinal-perceptrons;camadaFinal-perceptrons
#onde camadaFinal é a última camada a ter esta quantidade, então no exemplo 3-11;5;12;7-11 com 7 camadas o resultado vai ser:
#camadas de 1 a 3 , 11 perceptrons e de  5 a 6 12 perceptrons e a última volta a ter 11
#outro exemplo, se todas as 7 camadas tivessem 13 perceptros seria apenas 7-784 pois só se registra as camadas finais de cada mudançá 
perceptions=3-784